# Generated by Django 4.1.7 on 2023-02-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_date',
            new_name='date',
        ),
    ]
